name: mustafa_portfolio
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # my packages
  easix: ^0.0.4

  # packages
  connectivity_plus: ^4.0.2
  dio: ^5.3.2
  get_it: ^7.6.2
  go_router: ^10.1.2
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  flutter_hooks: ^0.20.1
  animate_do: ^3.0.2
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  google_fonts: ^5.1.0
  line_awesome_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
