name: mustafa_portfolio
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Bloc
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5

  # my packages
  easix: ^1.1.0

  # packages
  connectivity_plus: ^6.0.3
  #  dio: ^5.4.3+1
  get_it: ^7.7.0
  go_router: ^14.1.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  flutter_hooks: ^0.20.5
  animate_do: ^3.3.4
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  responsive_framework: ^1.4.0
  url_launcher: ^6.2.6
  url_launcher_web: ^2.3.1
  # firebase_core: ^2.31.0
  #  firebase_auth: ^4.19.5
  # firebase_storage: ^11.7.5
  # firebase_database: ^10.5.5
  carousel_slider: ^4.2.1
  easy_image_viewer: ^1.5.0
  supabase_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/me.jpg"
  min_sdk_android: 25
  web:
    generate: true
    image_path: "assets/me.jpg"
  windows:
    generate: true
    image_path: "assets/me.jpg"
  macos:
    generate: true
    image_path: "assets/me.jpg"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
