name: mustafa_portfolio
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # my packages
  easix: ^1.0.2

  # packages
  connectivity_plus: ^5.0.2
  dio: ^5.3.2
  get_it: ^7.6.2
  go_router: ^13.2.1
  flutter_svg: ^2.0.7
  intl: ^0.19.0
  flutter_hooks: ^0.20.1
  animate_do: ^3.0.2
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.5.0
  responsive_framework: ^1.1.0
  url_launcher: ^6.1.14
  url_launcher_web: ^2.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  firebase_database: ^10.4.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/me.jpg"
  min_sdk_android: 25
  web:
    generate: true
    image_path: "assets/me.jpg"
  windows:
    generate: true
    image_path: "assets/me.jpg"
  macos:
    generate: true
    image_path: "assets/me.jpg"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
