// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRup95MZ1-AVH2KXp_Uh10GGUBejOApxA',
    appId: '1:96917966797:web:7d7c202a39359f62e9fe84',
    messagingSenderId: '96917966797',
    projectId: 'mustafaix',
    authDomain: 'mustafaix.firebaseapp.com',
    databaseURL: 'https://mustafaix-default-rtdb.firebaseio.com',
    storageBucket: 'mustafaix.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5O64UpmvNfYnCI0AnCJpK_31QzgV7JEg',
    appId: '1:96917966797:android:93a88dc1b2742f2de9fe84',
    messagingSenderId: '96917966797',
    projectId: 'mustafaix',
    databaseURL: 'https://mustafaix-default-rtdb.firebaseio.com',
    storageBucket: 'mustafaix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY_6isAY37AhqQ12AEfTveI8ovSW-pY8I',
    appId: '1:96917966797:ios:80e12818777d11d1e9fe84',
    messagingSenderId: '96917966797',
    projectId: 'mustafaix',
    databaseURL: 'https://mustafaix-default-rtdb.firebaseio.com',
    storageBucket: 'mustafaix.appspot.com',
    iosBundleId: 'com.example.mustafaPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY_6isAY37AhqQ12AEfTveI8ovSW-pY8I',
    appId: '1:96917966797:ios:5b482b55e7601c95e9fe84',
    messagingSenderId: '96917966797',
    projectId: 'mustafaix',
    databaseURL: 'https://mustafaix-default-rtdb.firebaseio.com',
    storageBucket: 'mustafaix.appspot.com',
    iosBundleId: 'com.example.mustafaPortfolio.RunnerTests',
  );
}
